name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      env:
        USER: ${{ secrets.USER }}
        PASS: ${{ secrets.PASS }}
      run: |
        echo $USER
        echo $PASS
        docker build . --gile Dockerfile --tag MukundWaghmare27/:latest
        docker login -u $USER -p PASS

        docker push MukundWaghmare27/github:latest



        
